on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version'

name: Build and publish

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: npm i

      - name: Test
        run: npm run test

      - name: Build domdom
        run: npm run build

      - name: Git config
        run: |
          git config --global user.name 'Eirik Brandtzæg'
          git config --global user.email 'eirikb@eirikb.no'

      - name: Install extra
        run: npm i --no-save shelljs puppeteer http-server gifencoder png-js ts-node

      - name: Build readme
        run: |
          cd readme
          ../node_modules/.bin/ts-node build.ts

      - name: Git commit
        run: git commit -am "Updated readme"

      - name: Set version
        run: npm version ${{ github.event.inputs.version }}

      - name: Git push
        run: git push

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          tag_name: v${{ github.event.input.version }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
